version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  nginx:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src
    ports:
      - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
    links:
      - web

  python:
    build: .
    command: /bin/true
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: 'True'
      DEV_ENV: 'True'
      NODE_ENV: 'development'
      PORT: {{ cookiecutter.internal_port }}
      COVERAGE_DIR: htmlcov
      DATABASE_URL: postgres://postgres@db:5432/postgres
      {{ cookiecutter.project_name|upper }}_USE_WEBPACK_DEV_SERVER: 'True'
      {{ cookiecutter.project_name|upper }}_SECURE_SSL_REDIRECT: 'False'
      {{ cookiecutter.project_name|upper }}_DB_DISABLE_SSL: 'True'
      ELASTICSEARCH_URL: elastic:9200
      CELERY_TASK_ALWAYS_EAGER: 'False'
      CELERY_BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      WEBPACK_DEV_SERVER_HOST: ${WEBPACK_DEV_SERVER_HOST:-localhost}
    env_file: .env

  web:
    image: {{ cookiecutter.project_name }}_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py collectstatic --noinput &&
      python3 manage.py migrate --noinput &&
      uwsgi uwsgi.ini'
    ports:
      - "{{ cookiecutter.internal_port }}:{{ cookiecutter.internal_port }}"
    links:
      - db
      - redis

  watch:
    build:
      context: .
      dockerfile: Dockerfile-node
    working_dir: /src
    command: >
      /bin/bash -c './webpack_dev_server.sh --install'
    ports:
      - "{{ cookiecutter.webpack_dev_port }}:{{ cookiecutter.webpack_dev_port }}"
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn
    environment:
      NODE_ENV: 'development'
      DOCKER_HOST: ${DOCKER_HOST:-missing}
      CONTAINER_NAME: 'watch'
    env_file: .env

  celery:
    image: {{ cookiecutter.project_name }}_python
    extends:
      service: python
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A {{ cookiecutter.project_name }} worker -B -l debug'
    links:
      - db
      - redis

volumes:
  django_media: {}
  yarn-cache: {}
