db:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python3 manage.py migrate &&
    ./with_host.sh python3 manage.py runserver 0.0.0.0:{{ cookiecutter.port }}'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    NODE_ENV: 'development'
    PORT: {{ cookiecutter.port }}
    COVERAGE_DIR: htmlcov
    DATABASE_URL: postgres://postgres@db:5432/postgres
    {{ cookiecutter.project_name|upper }}_USE_WEBPACK_DEV_SERVER: 'True'
    {{ cookiecutter.project_name|upper }}_SECURE_SSL_REDIRECT: 'False'
    {{ cookiecutter.project_name|upper }}_DB_DISABLE_SSL: 'True'
  env_file: .env
  ports:
    - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
  links:
    - db

watch:
  image: {{ cookiecutter.project_name|replace("_","") }}_web
  command: >
    /bin/bash -c '
    npm cache clean &&
    npm install --no-bin-links &&
    npm rebuild node-sass &&
    echo Finished npm install &&
    node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config webpack.config.dev.js -d --content-base ./static --host 0.0.0.0 --port {{ cookiecutter.webpack_dev_port }} --progress --inline --hot'
  ports:
    - "{{ cookiecutter.webpack_dev_port }}:{{ cookiecutter.webpack_dev_port }}"
  volumes:
    - .:/src
  env_file: .env
  environment:
    NODE_ENV: 'development'
