db:
  image: postgres
  ports:
    - "5432"

web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python3 manage.py migrate &&
    ./with_host.sh python3 manage.py runserver 0.0.0.0:{{ cookiecutter.port }}'
  volumes:
    - .:/src
  environment:
    DEBUG: 'True'
    NODE_ENV: 'development'
    PORT: {{ cookiecutter.port }}
    COVERAGE_DIR: htmlcov
    DATABASE_URL: postgres://postgres@db:5432/postgres
    {{ cookiecutter.project_name|upper }}_USE_WEBPACK_DEV_SERVER: 'True'
    {{ cookiecutter.project_name|upper }}_SECURE_SSL_REDIRECT: 'False'
    {{ cookiecutter.project_name|upper }}_DB_DISABLE_SSL: 'True'
  env_file: .env
  ports:
    - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
  links:
    - db

watch:
  build: .
  dockerfile: Dockerfile-node
  working_dir: /src
  command: >
    /bin/bash -c './webpack_dev_server.sh --install'
  ports:
    - "{{ cookiecutter.webpack_dev_port }}:{{ cookiecutter.webpack_dev_port }}"
  volumes:
    - .:/src
  environment:
    NODE_ENV: 'development'
  env_file: .env
