web: bin/start-nginx bin/start-pgbouncer-stunnel newrelic-admin run-program uwsgi uwsgi.ini
worker: bin/start-pgbouncer newrelic-admin run-program celery -A {{ cookiecutter.project_name }}.celery:app worker -B -l ${{ cookiecutter.project_name|upper }}_LOG_LEVEL
extra_worker: bin/start-pgbouncer newrelic-admin run-program celery -A {{ cookiecutter.project_name }}.celery:app worker -l ${{ cookiecutter.project_name|upper }}_LOG_LEVEL
