web: bin/start-nginx bin/start-pgbouncer-stunnel newrelic-admin run-program uwsgi uwsgi.ini
worker: celery -A {{ cookiecutter.project_name }} worker -B -l ${{ cookiecutter.project_name|upper }}_LOG_LEVEL
extra_worker: celery -A {{ cookiecutter.project_name }} worker -l ${{ cookiecutter.project_name|upper }}_LOG_LEVEL
