web: bin/start-nginx bin/start-pgbouncer-stunnel newrelic-admin run-program uwsgi uwsgi.ini
worker: celery -A {{ cookiecutter.project_name }} worker -B
extra_worker: celery -A {{ cookiecutter.project_name }} worker
