db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  command: >
    /bin/bash -c '
    sleep 3 &&
    python3 manage.py migrate &&
    ./with_host.sh python3 manage.py runserver 0.0.0.0:{{ cookiecutter.port }}'
  environment:
    DEBUG: 'False'
    COVERAGE_DIR: htmlcov
    PORT: {{ cookiecutter.port }}
    NODE_ENV: 'production'
    DATABASE_URL: postgres://postgres@db:5432/postgres
    {{ cookiecutter.project_name|upper }}_SECURE_SSL_REDIRECT: 'False'
    {{ cookiecutter.project_name|upper }}_DB_DISABLE_SSL: 'True'
  ports:
    - "{{ cookiecutter.port }}:{{ cookiecutter.port }}"
  links:
    - db
