language: python
dist: xenial
python:
  - "3.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
  - pip install -r test_requirements.txt
script:
  - tox
services:
  - docker
