name: CI
on: [push]
jobs:
  python-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11.6
        # Health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

      redis:
        image: redis:5.0.8
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Apt install
        run: cat Aptfile | sudo xargs apt-get install

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ "{{" }} runner.os }}-pip-${{ "{{" }} hashFiles('**/requirements.txt', '**/test_requirements.txt') }}
          restore-keys: |
            ${{ "{{" }} runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt -r test_requirements.txt

      - name: Lint
        run: pylint ./**/*.py
        env:
          DJANGO_SETTINGS_MODULE: "main.settings"
          PYTHONPATH: "."

      - name: Black
        run: black --check .

      - name: Tests
        run: |
          export MEDIA_ROOT="$(mktemp -d)"
          sudo mkdir /var/media
          sudo chown -R $USER:$USER /var/media
          ./scripts/test/python_tests.sh
        env:
          {{ cookiecutter.project_name|upper }}_DB_DISABLE_SSL: 'True'
          {{ cookiecutter.project_name|upper }}_SECURE_SSL_REDIRECT: 'False'
          CELERY_TASK_ALWAYS_EAGER: 'True'
          CELERY_BROKER_URL: redis://localhost:6379/4
          CELERY_RESULT_BACKEND: redis://localhost:6379/4
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
          DEBUG: 'False'
          MAILGUN_URL: 'http://fake.example.com'
          MAILGUN_KEY: 'fake'
          NODE_ENV: 'production'

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  javascript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.15.1"

      - name: Setup environment
        run: sudo apt-get install libelf1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ "{{" }} steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ "{{" }} runner.os }}-yarn-${{ "{{" }} hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ "{{" }} runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines --prefer-offline

      - name: Lints
        run: npm run lint

      - name: Code formatting
        run: npm run fmt:check

      - name: Scss lint
        run: npm run scss_lint

      - name: Tests
        run: npm run test
        env:
          CODECOV: true
          NODE_ENV: development

      - name: Webpack build
        run: node node_modules/webpack/bin/webpack.js --config webpack.config.prod.js --bail

      - name: Upload test coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          file: coverage/lcov.info
          fail_ci_if_error: true
